project:
  name: "Plant"
  version: 0.1.1
  description: python requests for filesystem
  github_maintainer: gabrielfalcao
  github_maintainer_name: Gabriel Falc&atilde;o

documentation:
  index: intro.md

toc:
  - intro.md
  - find-files.md
  - string-operations.md
  - traversing-paths.md
