project:
  name: "Plant"
  version: 0.1.0
  description: python file-system <br /> for humans

  github_maintainer: gabrielfalcao
  github_maintainer_name: Gabriel Falc&atilde;o
  github_maintainer_url: http://github.com/gabrielfalcao
  github_maintainer_gravatar: https://secure.gravatar.com/avatar/3fa0df5c54f5ac0f8652d992d7d24039?s=64

  github_url: http://github.com/gabrielfalcao/plant
  github_fork_url: https://github.com/gabrielfalcao/plant/archive/master.tar.gz
  tarball_download_url: https://github.com/gabrielfalcao/plant/archive/master.tar.gz
  zipball_download_url: https://github.com/gabrielfalcao/plant/archive/master.zip

  logo_path: images/logo.png
  logo_inline_css: "display: block"

documentation:
  index: intro.md
